// var Promise = require("bluebird");
// it seems no need to use bluebird promises anymore...
    // earlier promises of nodeJS (v8, v12) may be slow & stuff
    // but now, native promises are fast enough...
    // see this link ===> https://github.com/petkaantonov/bluebird/